Feat. 다운로드 페이지 생성
KrossCutting/KrossCutting-app pull request #11
Opened 2024-02-25 14:03 UTC by sht02048

# KanBan Title
- [프로그래스 및 다운로드 스크린](https://minsug.notion.site/app-bc7869b729b7497e804b1bc77f216fb0?pvs=4)

# Tasks in detail - checkList
- [x] 다운로드 페이지 구현
- [x] 다운로드 로직 구현 
- [x] 프로그래스 페이지 연결 

# Description
- POST 요청과 GET 요청을 모두 핸들링할 수 있게 progress_screen 페이지를 수정했습니다.
- 편집이 모두 끝난 후에 홈으로 이동하며 홈에 있는 다운로드 버튼을 통해 갤러리에 영상을 저장합니다.

# remarks
- `gallery_saver `등 패키지 설치로 flutter pub get 부탁드립니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-25 15:59 UTC, zzinLee commented on lib/screens/instruction_page/instrunction_coach_mark.dart
> +              Navigator.popUntil(
`popUntil` 초기 화면까지 구동시켜 라우터 내역을 말끔히 삭제하고, 코치마크 내역도 삭제하니 훨씬 더 좋습니다.
👍

2024-02-25 16:00 UTC, alswla requested changes
민석님! 스크린 위젯 구현뿐만 아니라 서버와 연결하시느라 고생 많으셨습니다!🙇‍♀️ 코멘트 확인 부탁드리겠습니다!

2024-02-25 16:00 UTC, alswla commented on lib/screens/download_screen.dart
> +      return file;
변수선언과 로직 사이에 인덴팅 한줄 추가해주시면 좋을 것 같아요! :)

2024-02-25 16:00 UTC, alswla commented on lib/screens/download_screen.dart
> +          await GallerySaver.saveVideo(filePath, albumName: "krosscutting");
인덴팅 부탁드립니다!

2024-02-25 16:00 UTC, alswla commented on lib/screens/download_screen.dart
> +  }
해당 부분도 전체적으로 인덴팅 해주시면 가독성이 좋아질 것 같습니다 👍

2024-02-25 16:00 UTC, alswla commented on lib/screens/download_screen.dart
> +                'assets/images/checkmark.json',
쌍따옴표로 맞춰주시면 좋을 것 같아요!

2024-02-25 16:00 UTC, alswla commented on lib/screens/home_screen/home_screen.dart
> +                      )
```suggestion
                     HomeButtonDotted(
                        onClick = onClickAction ?? () {},
                        color = buttonColor,
                     )
```

2024-02-25 16:00 UTC, alswla commented on lib/screens/home_screen/home_screen.dart
> +    final downloadUrl = Provider.of<DownloadUrlProvider>(context).finalVideoUrl;
민석님! 아래와 같이 기본값을 먼저 정의한다면 아래 삼항연산자 부분을 좀 더 간결하게 사용할 수 있을 것 같습니다!
하지만 지금도 가독성이 나쁘지 않다고 생각되어 참고만 부탁드리겠습니다! 🙇‍♀️

```suggestion
    final videoDirection = Provider.of<VideoDirectionProvider>(context);
    final downloadUrl = Provider.of<DownloadUrlProvider>(context).finalVideoUrl;
    
    VoidCallback? onClickAction;
    Color buttonColor = Colors.grey[800]!; 

    if (downloadUrl != "") {
      onClickAction = () => Navigator.pushNamed(context, "/downloadScreen");
      buttonColor = Colors.purpleAccent;
    }
```

2024-02-25 16:00 UTC, alswla commented on lib/screens/select_screen/start_point_controller.dart
> +                                  },
swipe 이벤트를 막아주셨군요! 🙇‍♀️👍

2024-02-25 16:00 UTC, alswla commented on lib/utils/utils.dart
> +  };
민석님! 해당 부분 무조건 3개의 영상을 필요로 하는 것 같은데 맞을까요? 맞다면 해당 부분 2개의 영상에도 적용될 수 있도록 TODO로 써놔주시면 감사하겠습니다!

2024-02-25 16:11 UTC, zzinLee submitted a review, later dismissed
민석님, 코드가 깔끔해서 모두 알아볼 수 있었습니다. 모두 확인했습니다!

2024-02-26 04:43 UTC, sht02048 commented on lib/utils/utils.dart
> +  };
아 넵넵 민지님 코드를 제가 변경해놓았네요 다시 복구했습니다!

2024-02-26 04:43 UTC, sht02048 commented on lib/screens/home_screen/home_screen.dart
> +    final downloadUrl = Provider.of<DownloadUrlProvider>(context).finalVideoUrl;
이렇게 하니 가독성이 훨씬 좋네요! 변경해놓겠습니다~

2024-02-26 05:21 UTC, alswla approved these changes
수고하셨습니다 민석님!! 👍

2024-02-26 06:23 UTC, zzinLee approved these changes

2024-02-26 06:26 UTC, merged