Refactor. 라우터 최적화
KrossCutting/KrossCutting-app pull request #12
Opened 2024-02-26 11:13 UTC by sht02048

# KanBan Title
- 해당 칸반 x

# Tasks in detail - checkList
- [x] swipe back 비활성화
- [x] 아이콘 이미지 변경
- [x] 튜토리얼 UI 바뀐 컨트롤러에 최적화  

# Description
- 시작점과 편집점을 선택하는 화면에서 swipe back을 하면 이전 비디오로 돌아가는 것이 아니라 이전 라우트로 변경되는 버그가 있어 수정하였습니다. 
- 아이콘을 기본 flutter 이미지에서 krosscutting 이미지로 변경했습니다.
- 비디오 컨트롤러 UI가 바뀜에 따라 튜토리얼 UI도 변경했습니다.

# 주의 사항
- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트
- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-02-26 11:26 UTC, zzinLee commented on lib/screens/select_screen/start_point_controller.dart
> +                                    // );
민석님, 이 부분 주석 남겨두신 이유가 있을까요? 
사용하지 않을 예정이시면 삭제해도 좋을 것 같습니다!

2024-02-26 11:27 UTC, zzinLee requested changes
민석님! 주석 관련 내용 한번만 확인해주세요 :)

2024-02-26 11:41 UTC, sht02048 commented on lib/screens/select_screen/start_point_controller.dart
> +                                    // );
넵 바로 수정하겠습니다!

2024-02-27 01:29 UTC, alswla commented on lib/screens/select_screen/start_point_controller.dart
> +                                          true, // This disables the swipe back on iOS.
민석님 해당 부분 주석 삭제 부탁드립니다!

2024-02-27 01:29 UTC, alswla reviewed
민석님 라우터 작업 수고하셨습니다! 주석관련 코멘트만 확인 부탁드립니다!

2024-02-27 04:27 UTC, alswla approved these changes
확인했습니다 민석님! 수고하셨습니다~

2024-02-27 04:27 UTC, zzinLee approved these changes
Swipe오류 안그래도 확인하고 있었는데, 발빠르게 처리해주셨네요 👍 
감사합니다. 고생하셨습니다 ~!

2024-02-27 04:54 UTC, merged